name: CI workflow

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install front
        run: |
          cd front
          npm install
      - name: Install back
        run: |
          cd back
          npm install
      - name: Build
        run: |
          cd front
          npm run build
      - name: Tests front
        run: |
          cd front
          npm test
      - name: Tests back
        run: |
          cd back
          npm test
