name: Develop CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: lemoncode/actions/aws-ebs-action.yml@main
        with:
          files-to-zip: "back/** back/.babelrc  front/** front/.babelrc Dockerfile .dockerignore"
          dockerArgs: BASE_API_URL=${{secrets.DEV_BASE_API_URL}}
          AWS_EB_APP_NAME: ${{secrets.DEV_AWS_EB_APP_NAME}}
          AWS_EB_ENV_NAME: ${{secrets.DEV_AWS_EB_ENV_NAME}}
          AWS_DEPLOY_ACCESS_KEY_ID: ${{secrets.DEV_AWS_DEPLOY_ACCESS_KEY_ID}}
          AWS_DEPLOY_SECRET_ACCESS_KEY: ${{secrets.DEV_AWS_DEPLOY_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.DEV_AWS_REGION}}
          AWS_DEPLOY_S3_BUCKET: ${{secrets.DEV_AWS_DEPLOY_S3_BUCKET}}
