name: Develop CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  dev-cd:
    uses: lemoncode/actions/.github/workflows/aws-ebs.yml@main
    with:
      files-to-zip: "back/** back/.babelrc  front/** front/.babelrc Dockerfile .dockerignore"
      dockerArgs: BASE_API_URL=${{secrets.DEV_BASE_API_URL}}
    secrets: inherit
