name: Develop CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - develop
env:
  IMAGE_NAME: ghcr.io/lemoncode/planning-poker-example:dev-${{github.run_number}}-${{github.run_attempt}}

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: https://dev-tshirtplanning.azurewebsites.net
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        run: |
          docker build \
          --build-arg BASE_API_URL=https://dev-tshirtplanning.azurewebsites.net \
          --build-arg BASE_APP_URL=https://dev-tshirtplanning.azurewebsites.net \
          -t ${{env.IMAGE_NAME}} .
          docker push ${{env.IMAGE_NAME}}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.DEV_AZURE_APP_NAME }}
          publish-profile: ${{ secrets.DEV_AZURE_PUBLISH_PROFILE }}
          images: ${{env.IMAGE_NAME}}
