name: Production CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  prod-cd:
    uses: lemoncode/actions/.github/workflows/aws-ebs.yml@main
    with:
      files-to-zip: 'back/** back/.babelrc  front/** front/.babelrc Dockerfile .dockerignore' 
    secrets:
      AWS_EB_APP_NAME: ${{secrets.AWS_EB_APP_NAME}}
      AWS_EB_ENV_NAME: ${{secrets.AWS_EB_ENV_NAME}}
      AWS_DEPLOY_ACCESS_KEY_ID: ${{secrets.AWS_DEPLOY_ACCESS_KEY_ID}}
      AWS_DEPLOY_SECRET_ACCESS_KEY: ${{secrets.AWS_DEPLOY_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_DEPLOY_S3_BUCKET: ${{secrets.AWS_DEPLOY_S3_BUCKET}}
