name: Production CD Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  IMAGE_NAME: ghcr.io/lemoncode/planning-poker-example:prod-${GITHUB_SHA}-${GITHUB_RUN_ATTEMPT}

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: https://tshirtplanning.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        run: |
          docker build \
          --build-arg BASE_API_URL=https://tshirtplanning.com \
          --build-arg BASE_APP_URL=https://tshirtplanning.com \
          -t ${{env.IMAGE_NAME}} -f azure.Dockerfile .
          docker push ${{env.IMAGE_NAME}}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_NAME }}
